# Site settings
title:       David Ni
email:       david@davidni.com
author:      David Ni
description: "David Ni's Blog"
baseurl:     ""
url:         "http://davidni.com"
date_format: "%b %-d, %Y"

# Google services
google_analytics: UA-62017858-2
google_verification:

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10

# Social icons
github_username: jominione
bitbucket_username:
stackoverflow_id:
twitter_username: ThePoliEcon
google_plus_id:
linkedin_username: david-ni-48a58b74
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     7
sass:
  compressed: true
